version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      # 将SQL文件挂载到容器的初始化目录
      - ./sql/tables:/docker-entrypoint-initdb.d/
    restart: unless-stopped